name: Push to NuGet

on:
  workflow_run:
    workflows: ["Build and Pack"]
    types:
      - completed
  workflow_dispatch:

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Package
      uses: actions/download-artifact@v4
      with:
        name: nuget-package
        path: ./SimpleHttp/SimpleHttpClient/bin/Release
    - name: Download Version
      uses: actions/download-artifact@v4
      with:
        name: package-version
        path: .
    - name: Read Version
      id: read_version
      run: echo "PACKAGE_VERSION=$(cat version.txt)" >> $GITHUB_ENV
    - name: Push NuGet package
      run: dotnet nuget push ./SimpleHttp/SimpleHttpClient/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}